version: 1
disable_existing_loggers: false
filters: {}
formatters:
  verbose:
    format: '%(asctime)s -%(levelname)s %(process)d,%(thread)d %(funcName)s %(filename)s:%(lineno)s %(message)s'
handlers:
  default:
    level: DEBUG
    class: concurrent_log_handler.ConcurrentRotatingFileHandler
    filename: logs/scheduler.log
    maxBytes: 10485760
    backupCount: 2
    formatter: verbose
    encoding: utf-8
  console:
    level: DEBUG
    class: logging.StreamHandler
    formatter: verbose
root:
  level: INFO
  handlers:
  - default
  - console
