# @Time    : 2024/10/18 16:04
# @Author  : frank
# @File    : sms_constant.py


class SmsConstant:
    """短信验证码模板常量。"""

    TYPE_LOGIN_REGISTER = "100001"

    TYPE_CHANGE_BIND_OLD = "100002"

    TYPE_RESET_PASSWORD = "100003"

    TYPE_BIND_NEW = "100004"

    TYPE_VERIFY_BIND = "100005"

    TYPE_LOGIN = TYPE_LOGIN_REGISTER

    TYPE_REGISTER = TYPE_LOGIN_REGISTER

    TYPE_REGISTER_NOTICE = TYPE_LOGIN_REGISTER

    TYPE_CHANGE_BIND = TYPE_CHANGE_BIND_OLD

    TYPE_FIND_PASSWORD = TYPE_RESET_PASSWORD

    TYPE_CHANGE_PASSWORD = TYPE_VERIFY_BIND
